// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjetoSimplesES;

/************************************************************/
/**
 * 
 */
public class Cliente extends Pessoa {
	/**
	 * 
	 */
	public undef dataCadastro;
}
