// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjetoSimplesES;

/************************************************************/
/**
 * 
 */
public class Funcionario extends Pessoa {
	/**
	 * 
	 */
	public undef pis;
}
