// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 * 
 */
public class Loja {
	/**
	 * 
	 */
	public undef telefone;
	/**
	 * 
	 */
	public Cliente cliente;
	/**
	 * 
	 */
	public Funcionario funcionario;
}
